### ISSUE TITLE
Be albe to disable the ability to change master key

### ISSUE THREAD

**Issue by JordyMoos** [JordyMoos/elm-yapm-client#59]
If we can configure in config.js that you can not update the master key (should then also be configures on the server) then we can host a demo of YAPM without fearing that a  funny user changes the master key and other users can not access it anymore.

**Comment by marcusklaas** [comment]
Good idea! I like it.

**Comment by JordyMoos** [comment]
Do we remove the "New Master Key" button or do we just show an error message when you click on the save button?

**Comment by marcusklaas** [comment]
Hmmm not sure... maybe grey it out? That way we show that it's usually possible, but disabled for the demo?
