### ISSUE TITLE
Scroll-then-fix header?

### ISSUE THREAD

**Issue by marcusklaas** [JordyMoos/elm-yapm-client#69]
Zoekbalk + knoppen mee laten scrollen op mobile?

Het mooiste zou het zijn als dit in enkel css kan, maar meeste implementaties die ik tot nu heb gezien gebruiken javascript om de `display` attribute van `relative` naar `fixed` te wijzigen.

ping @bhalial

**Comment by bhalial** [comment]
Use JavaScript to detect scroll, and based on that add a class to the header that will either transformY(-100%) or transformY(0). Also you can try to set a minimum offset from the top to trigger the disappearance of the header.

**Comment by JordyMoos** [comment]
This is included in mdl. Is not it worth it too try mdl out?
Then we have nice css, its build for mobile web, we have the header, and some left side bar menu in-out button. And buttons in the main get scroll (horizontal) buttons if not all the buttons fit.

**Comment by JordyMoos** [comment]
To answer your question: I do think it is an enchantment to have the header always be visible

**Comment by marcusklaas** [comment]
OMG dit kan tegenwoordig gewoon in CSS :D 🎆 🍾 🙌 🎊  🥒 

http://gedd.ski/post/position-sticky/

**Comment by marcusklaas** [comment]
Dit wordt dope. PR incoming!

**Comment by JordyMoos** [comment]
Top. Nice dat er weer ff aan gewerkt wordt!

Als ik tijd vrij heb probleer een een docker setup te maken met auto letsencrypt systeem.
Zodat het voor iedereen makkelijk is dit zelf te hosten
