### ISSUE TITLE
Pre fillin a random password when creating a new password

### ISSUE THREAD

**Issue by JordyMoos** [JordyMoos/elm-yapm-client#75]
I always create a random password. So for me it would be useful if a random password is already filled in when i come to the new password form.

Optionally we could make it configurable if you want to have this feature.

Your thoughts on this?

**Comment by marcusklaas** [comment]
Yea, that's what I do 9 times out of 10 as well.

I always have to look up the password after saving it, for example when creating a new account somewhere. Perhaps we could even make this easier by adding a copy button in the dialogue?

**Comment by JordyMoos** [comment]
Good one I have that same work flow. Let's add that copy button too. 

Do we add a configuration for this auto password. Or should we always so it
